import javax.swing.*;
import java.awt.*;
public class CharacterWindow extends JFrame {
    CharacterWindow(CharacterCreation name){
        JFrame frameCharacter = new JFrame(name.name + "'s Stats");
        frameCharacter.setLayout(new GridLayout(37, 3));
        JLabel labelName = new JLabel("LVL "+name.currentLevel + " " +name.name);
        JLabel labelXP = new JLabel("EXP: "+name.currentXP+"/"+name.xpGainLevel);
        JLabel labelHP = new JLabel("HP: "+name.currentHP+"/"+name.maxHp);
        JLabel labelEnergy = new JLabel("EG: "+name.currentEnergy+"/"+name.maxEnergy);
        JLabel labelSpirit = new JLabel("SPR: "+name.currentSpirit+"/"+name.maxSpirit);
        JLabel labelMoral = new JLabel("Morality"+"\n"+"-------------");
        JLabel labelGood = new JLabel("GOOD: "+name.goodMoral);
        JLabel labelNeutral = new JLabel("NEUTRAL: "+name.neutralMoral);
        JLabel labelBad = new JLabel("BAD: "+name.badMoral);
        JLabel labelMoralPoints = new JLabel("Points available: "+name.moralityPoints);
        JLabel labelChakras = new JLabel("Chakras"+"\n"+"-------------");
        JLabel labelCrown = new JLabel("CROWN: "+name.crownChakra);
        JLabel labelThird = new JLabel("THIRD: "+name.thirdEyeChakra);
        JLabel labelThroat = new JLabel("THROAT: "+name.throatChakra);
        JLabel labelHeart = new JLabel("HEART: "+name.heartChakra);
        JLabel labelSolar = new JLabel("SOLAR: "+name.solarPlexusChakra);
        JLabel labelSacral = new JLabel("SACRAL: "+name.sacralChakra);
        JLabel labelRoot = new JLabel("ROOT: "+name.rootChakra);
        JLabel labelChakraPoints = new JLabel("Points available: "+name.chakraPoints);
        JLabel labelModifiers = new JLabel("Modifiers"+"\n"+"-----------");
        JLabel labelPhysAtk = new JLabel("PhysDMG "+name.physAtk);
        JLabel labelMagAtk= new JLabel("MagDMG "+name.magAtk);
        JLabel labelPhysDef = new JLabel("PhsyDEF "+name.physDef);
        JLabel labelMagDef= new JLabel("MagDEF "+name.magDef);
        JLabel labelSpeed = new JLabel("Speed "+name.charSpeed);
        JLabel labelEvasion = new JLabel("Evasion " +(name.evasion * 100)+"%");
        JLabel labelBlockChance = new JLabel("Block Chance "+(name.blockChance * 100)+"%");
        JLabel labelCritChance = new JLabel("Crit Chance "+(name.critChance * 100)+"%");
        JLabel labelCritMult = new JLabel("Crit Multiplier "+name.critMult+"x");
        JLabel labelRes = new JLabel("Resisitances"+"\n"+"------------");
        JLabel labelHoly = new JLabel("Holy "+(name.holyDef*100)+"%");
        JLabel labelDark = new JLabel("Dark "+(name.darkDef*100)+"%");
        JLabel labelAir = new JLabel("Fire "+(name.fireDef*100)+"%");
        JLabel labelEarth = new JLabel("Earth "+(name.earthDef*100)+"%");
        JLabel labelFire = new JLabel("Air "+(name.airDef*100)+"%");
        JLabel labelWater = new JLabel("Water "+(name.waterDef*100)+"%");
        JLabel labelChaos = new JLabel("Chaos "+(name.chaosDef*100)+"%");
        frameCharacter.add(labelName);
        frameCharacter.add(labelXP);
        frameCharacter.add(labelHP);
        frameCharacter.add(labelEnergy);
        frameCharacter.add(labelSpirit);
        frameCharacter.add(labelMoral);
        frameCharacter.add(labelGood);
        frameCharacter.add(labelNeutral);
        frameCharacter.add(labelBad);
        frameCharacter.add(labelMoralPoints);
        frameCharacter.add(labelChakras);
        frameCharacter.add(labelCrown);
        frameCharacter.add(labelThird);
        frameCharacter.add(labelThroat);
        frameCharacter.add(labelHeart);
        frameCharacter.add(labelSolar);
        frameCharacter.add(labelSacral);
        frameCharacter.add(labelRoot);
        frameCharacter.add(labelChakraPoints);
        frameCharacter.add(labelModifiers);
        frameCharacter.add(labelPhysAtk);
        frameCharacter.add(labelMagAtk);
        frameCharacter.add(labelPhysDef);
        frameCharacter.add(labelMagDef);
        frameCharacter.add(labelSpeed);
        frameCharacter.add(labelEvasion);
        frameCharacter.add(labelBlockChance);
        frameCharacter.add(labelCritChance);
        frameCharacter.add(labelCritMult);
        frameCharacter.add(labelRes);
        frameCharacter.add(labelHoly);
        frameCharacter.add(labelDark);
        frameCharacter.add(labelAir);
        frameCharacter.add(labelEarth);
        frameCharacter.add(labelFire);
        frameCharacter.add(labelWater);
        frameCharacter.add(labelChaos);
        frameCharacter.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frameCharacter.setSize(300, 300);
        frameCharacter.setVisible(true);

    }
}
